import com.example.Pizzeria.models.Pizza
import com.example.Pizzeria.models.PizzaReceipt
import com.example.Pizzeria.models.OrderDate
import com.example.Pizzeria.models.OrderTime
import com.example.Pizzeria.models.Discount
import com.example.Pizzeria.models.Drink
import com.example.Pizzeria.models.Topping
import java.math.BigDecimal

rule "Student ma 10% znizki"
	when
		pR: PizzaReceipt()
		p: Pizza(p.isStudent == true)
	then
	    pR.addDiscount(new Discount("student",BigDecimal.valueOf(0.1)));
	end
	
rule "Zamowiono wiecej niz 3 duze pizze"
	when
		pR: PizzaReceipt()
		p: Pizza(p.pizzaCount > 3 && p.pizzaSize.equals("Large"))

	then
		pR.addDiscount(new Discount("wiecejPizz",BigDecimal.valueOf(0.5)));
	end
	
rule "We wtorki Capriciosa tansza o 20 %"
	when
		pR: PizzaReceipt()
		oD: OrderDate(oD.dayOfWeek.equals("TUESDAY"))
		p: Pizza(p.pizzaType.equals("Capricciosa"))

	then
    	pR.addDiscount(new Discount("wtorki",BigDecimal.valueOf(0.2)));
	end

rule "Taniej przed poludniem"
   	when
  		pR: PizzaReceipt()
   		oT: OrderTime(oT.earlyTime == true)
  	then
       	pR.addDiscount(new Discount("przedPoludniem",BigDecimal.valueOf(0.2)));
    end

rule "Taniej z piciem"
   	when
   		pR: PizzaReceipt()
       	d: Drink(d.countDrink > 2)
   	then
           	pR.addDiscount(new Discount("taniejZPiciem",BigDecimal.valueOf(0.1)));
   	end

rule "Zamowiono zestaw"
  	when
   		pR: PizzaReceipt()
   		p: Pizza(p.pizzaCount > 2)
   		t: Topping(t.name.equals("Bacon") || t.name.equals("Pepperoni"))

  	then
   		pR.addDiscount(new Discount("zestaw",BigDecimal.valueOf(0.3)));
   	end